---
version: 2
updates:
- package-ecosystem: bun
  directory: /
  schedule:
   interval: weekly
   day: friday
  commit-message:
    prefix: fix(deps)
- package-ecosystem: docker
  directory: /
  schedule:
   interval: weekly
   day: friday
  commit-message:
    prefix: fix(deps)
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: friday
  commit-message:
    prefix: chore(actions)
