---
name: Bun CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  bun-lint:
    name: Bun Lint
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PUBLIC_STRIPE_KEY: ${{ secrets.PUBLIC_STRIPE_KEY }}
      SECRET_STRIPE_KEY: ${{ secrets.SECRET_STRIPE_KEY }}
      PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.PUBLIC_PAYPAL_CLIENT_ID }}
      SECRET_PAYPAL_CLIENT_ID: ${{ secrets.SECRET_PAYPAL_CLIENT_ID }}
    steps:
    - uses: actions/checkout@v6
    - uses: oven-sh/setup-bun@v2
    - run: bun install && bun run check
  bun-test:
    name: Bun Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: oven-sh/setup-bun@v2
    - uses: docker/setup-compose-action@v1
    - run: docker compose up -d --wait db
    - run: bun install && bun test ./src ./tests/integration
    - if: always()
      run: docker compose down -v

